# Generated by Django 3.2.4 on 2021-06-22 09:33

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Square', 'Square')], max_length=128)),
                ('size', models.CharField(max_length=128)),
                ('topings', multiselectfield.db.fields.MultiSelectField(choices=[('Onion', 'Onion'), ('Tomato', 'Tomato'), ('Corn', 'Corn'), ('Capsicum', 'Capsicum'), ('Cheese', 'Cheese'), ('Jalapeno', 'Jalapeno')], max_length=42)),
            ],
        ),
    ]
